[package]
name = "netfilum"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
chacha20poly1305 = "0.10.1"
clap = { version = "4.6.0", features = ["derive"] }
ctrlc = "3.5.2"
filetime = "0.2.27"
getrandom = "0.4.2"
libc = "0.2.183"
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
socket2 = "0.6.3"

[target.'cfg(windows)'.dependencies]
winfsp = { version = "0.12.4", features = ["system", "windows-62"] }
winfsp-sys = { version = "0.12.1", features = ["system"] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
] }

[target.'cfg(windows)'.build-dependencies]
winfsp = { version = "0.12.4", features = ["system"] }

[patch.crates-io]
winfsp-sys = { path = "vendor/winfsp-sys" }
